variables:
- group: Standard

jobs:

- job: Linux

  pool:
    vmImage: 'ubuntu 16.04'

  steps:  
  - script: |
      sudo apt-get install autotools-dev autoconf make m4 autopoint debhelper python3-all xsltproc itstool docbook-xsl docbook-xml
    displayName: 'Install Developer Base'

  - script: |
      ./autogen.sh
      ./configure
      make
      sudo make install
    displayName: 'Create package'  

  - task: gitmirror@0
    inputs:
      GitRepoUrl: 'https://$(GithubPAT)@github.com/saigkill/ignore-me'