# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Development Base
      run: |
        sudo apt-get update
        sudo apt-get install autotools-dev autoconf make m4 autopoint debhelper python3-all xsltproc itstool docbook-xsl docbook-xml dh-make docbook docbook-dsssl docbook-defguide dbtoepub docbook-xsl-doc-text docbook-xsl-saxon fop libsaxon-java libxalan2-java libxslthl-java xalan gettext-doc libmail-box-perl w3-recs opensp libxml2-utils

    # Runs a set of commands using the runners shell
    - name: Create Package
      run: |
        ./autogen.sh
        ./configure
        make
        sudo make install
